version: "3.9"
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  # web:
  #   build: ./app
  api:
    build: ./backend
    ports: 
      - 8080:80
