library(shiny)
library(datasets)

ui <- fluidPage(
  
  titlePanel("Proyección de renta para plataforma AirBnb"),
  
  sidebarLayout(
    # Barra derecha para seleccionar inputs
    sidebarPanel(
      # Select Inputs
      selectInput(inputId = "EventFinder",
                  label = "Alcaldia:",
                  choices = c("Benito Juarez",
                              "Miguel Hidalgo",
                              "Venustiano Carranza",
                              "Iztacalco",
                              "Tlalpan",
                              "Cuauhtemoc",
                              "Iztapalapa",
                              "Gustavo A. Madero",
                              "Alvaro Obregon",
                              "Azcapotzalco",
                              "Coyoacan",
                              "Milpa Alta",
                              "Xochimilco",
                              "La Magdalena Contreras",
                              "Cuajimalpa de Morelos",
                              "Tlahuac"), #Lista de Alcadias
                  width = "220px"),
      selectInput(inputId = "EventFinder",
                  label = "Colonia:",
                  choices = c("Sta Cruz Atoyac",
                              "Morales Seccion Palmas (Polanco)",
                              "Kennedy (U Hab)",
                              "Juventino Rosas I",
                              "Heroes De Padierna Ii",
                              "Guerrero Iv",
                              "Reforma Iztaccihuatl Norte",
                              "Purisima I",
                              "Prados De Cuautepec",
                              "Garcimarrero Reacomodo",
                              "El Manto",
                              "Del Gas (Ampl)",
                              "Daniel Garza",
                              "Condominio Del Bosque (Fracc)-Bosque De Tlalpan",
                              "Colinas De Tarango",
                              "Agricola Oriental Iii",
                              "Adolfo Lopez Mateos",
                              "Escandon I",
                              "Educacion",
                              "El Parque De Coyoacan (Fracc)",
                              "San Antonio Tecomitl (Pblo)",
                              "Carlos Hank Gonzalez",
                              "Vertiz Narvarte",
                              "Valle De Tepepan",
                              "Santiago Atzacoalco (Pblo)",
                              "Santa Martha Del Sur",
                              "Santa Cruz Meyehualco (Pblo)",
                              "Tepetongo",
                              "San Miguel (Barr)",
                              "San Lorenzo Atemoaya (Pblo)",
                              "San Juan De Aragon 1a Seccion (U Hab) Ii",
                              "San Gabriel",
                              "San Bernabe Ocotepec (Pblo)",
                              "Paseo De Las Lomas-San Gabriel",
                              "Porvenir",
                              "Noche Buena",
                              "Molino De Santo Domingo",
                              "Moctezuma 2a Seccion Iii",
                              "Villa De Cortes",
                              "Santa Maria La Ribera I",
                              "San Pedro Zacatenco (Pblo)",
                              "San Miguel Tehuisco-Los Angeles-Ayometitla",
                              "San Juan Tlihuaca (Pblo)",
                              "San Juan Tepepan",
                              "San Francisco",
                              "San Bartolo El Chico",
                              "Peralvillo Ii",
                              "Pedregal De Sto Domingo Iv",
                              "Olivar De Los Padres",
                              "Pantitlan Iii",
                              "Observatorio",
                              "Narvarte Ii",
                              "Molino De Rosas",
                              "Vergel De Coyoacan-Vergel Del Sur",
                              "Tetenco (Pje)",
                              "La Primavera",
                              "La Magdalena Culhuacan (Barr)",
                              "Independencia",
                              "Iman 580 (U Hab)",
                              "San Andres Tetepilco (Pblo)",
                              "Ramos Millan Bramadero Ii",
                              "Progreso Tizapan",
                              "El Santuario (Ampl)",
                              "El Mirador",
                              "Ejercito De Oriente (U Hab) Ii",
                              "Del Carmen",
                              "Churubusco Tepeyac",
                              "Lomas De Santa Fe",
                              "Acacias",
                              "Estado De Hidalgo",
                              "La Joyita",
                              "Zacahuitzco",
                              "Valle Gomez",
                              "La Polvorilla (Ampl)",
                              "Los Cerrillos Iii",
                              "Hipodromo Condesa",
                              "Salvador Diaz Miron",
                              "Toriello Guerra",
                              "Tlazintla",
                              "Sinatel (Ampl)",
                              "Guerrero Iii",
                              "Guadalupe Proletaria",
                              "Guadalupe Inn",
                              "Revolucion",
                              "Progreso Nacional I",
                              "Emiliano Zapata",
                              "El Arenal 1a Seccion",
                              "Desarrollo Urbano Quetzalcoatl  Iii",
                              "Colinas Del Bosque-Las Tortolas",
                              "Claveria",
                              "Los Reyes (Pblo)",
                              "Pueblo Quieto",
                              "Las Cuevitas",
                              "Chinampac De Juarez Ii",
                              "Americas Unidas-Del Lago",
                              "Agricultura",
                              "Adolfo Ruiz Cortines I",
                              "20 De Noviembre",
                              "Centro I",
                              "Canada Del Olivar (U Hab)",
                              "Tula (Barr)",
                              "Campestre Churubusco",
                              "Campamento 2 De Octubre I",
                              "Aviacion Civil",
                              "Aguilera",
                              "Lomas De Chapultepec Iii",
                              "Villa Panamericana 3era. Seccion (U Hab)",
                              "Vallejo Ii",
                              "Unidad Popular Tepeaca",
                              "Santa Ursula Coapa (Pblo)",
                              "Santa Rosa",
                              "Santa Cecilia Tepetlapa (Pblo)",
                              "San Pedro El Chico",
                              "San Marcos (Ampl)",
                              "Tlapechico",
                              "Portales Iii",
                              "Pedregal De Sto Domingo V",
                              "Pedregal De Sto Domingo Ix",
                              "Paraje San Juan",
                              "Ocho De Agosto",
                              "Nueva Argentina (Argentina Poniente)",
                              "Triunfo De La Republica",
                              "Santa Lucia",
                              "Ex Hipodromo De Peralvillo",
                              "Zapote-Luis Donaldo Colosio (U Habs)",
                              "Villa Verdun",
                              "Seccion Xvi",
                              "Santa Martha Acatitla",
                              "Santa Maria Malinalco (Pblo)",
                              "San Luis Tlaxialtemalco (Pblo)",
                              "San Bartolo Ameyalco (Pblo)",
                              "Popo",
                              "Piedad Narvarte",
                              "Tepeaca",
                              "Parques Del Pedregal",
                              "Progresista",
                              "Nativitas La Joya (Ampl)",
                              "Narciso Mendoza-Villa Coapa Super Manzana 1 (U Hab)",
                              "Morelos Ii",
                              "Doctores Iii",
                              "Cuatro Arboles",
                              "Ciudad Universitaria",
                              "Magdalena  Mixhuca",
                              "Villa Coapa (Rdcial)",
                              "Josefa Ortiz De Dominguez",
                              "Francisco I Madero",
                              "Huichapan",
                              "Barros Sierra",
                              "Tizapan_Tizapan San Angel",
                              "Tepalcates I",
                              "Taxquena",
                              "Militar 1 K Lomas De Sotelo (U Hab)",
                              "Huayatla",
                              "Heroes De 1910",
                              "Granjas San Antonio",
                              "Reforma Politica Ii",
                              "El Contadero",
                              "La Martinica",
                              "Villa Panamericana 7ma. Seccion (U Hab)",
                              "Santa Ursula Xitla",
                              "Santa Cecilia",
                              "Santa Catarina (Barr)",
                              "San Diego Ocoyoacac",
                              "Pemex Prados Del Rosario (U Hab)",
                              "Paulino Navarro",
                              "Obrera Iii",
                              "Narciso Mendoza-Villa Coapa Super Manzana 6 (U Hab)",
                              "Fuentes Del Pedregal",
                              "El Prado",
                              "Doctores Ii",
                              "Los Cedros (Fracc)",
                              "Lomas De Tepemecatl",
                              "Aguilas Pilares",
                              "Agricola Oriental Vi",
                              "Zapotla (Barr)",
                              "Agricola Oriental Vii",
                              "San Salvador Cuauhtenco (Pblo)",
                              "Selene 2da Secc",
                              "Tetelpan (Pblo)",
                              "La Raza",
                              "La Polvorilla",
                              "Hacienda San Juan-Rincon De San Juan-Chimali",
                              "Granjas Modernas-San Juan De Aragon (Ampl)",
                              "Granjas Esmeralda",
                              "Providencia",
                              "General Felipe Berriozabal",
                              "Santa Maria Aztahuacan (U Hab)",
                              "San Pablo (Barr)",
                              "San Lorenzo Huipulco",
                              "San Juan De Aragon 3a Seccion (U Hab) I",
                              "San Jose De Los Cedros Ii",
                              "Nonoalco-Tlatelolco (U Hab) Iii",
                              "Napoles (Ampl)",
                              "Moctezuma 2a Seccion Iv",
                              "Morelos I",
                              "Tecacalanco",
                              "La Noria Tepepan",
                              "Roma Sur I",
                              "El Sifon",
                              "Ejidos De San Pedro Martir Ii (Sur)",
                              "Cuchilla Ramos Millan",
                              "Ctm Ixa Culhuacan (U Hab)",
                              "Los Angeles",
                              "Lomas De Santa Fe Ii",
                              "Militar Marte",
                              "Lomas De Reforma",
                              "Lomas De Becerra",
                              "La Tortuga Xolalpa-Hco Colegio Militar",
                              "Las Tinajas",
                              "Chimalistac",
                              "Centro Urbano Tlalpan (U Hab)",
                              "Alpes (Ampl)",
                              "Caracol",
                              "Axotla",
                              "Estado De Hidalgo_",
                              "Gral C  A  Madrazo",
                              "Ahuehuetes Anahuac",
                              "Villa Milpa Alta (Pblo)",
                              "San Pedro Apostol (Barr)",
                              "Anahuac Lago Sur",
                              "Nextitla",
                              "Nonoalco-Tlatelolco (U Hab) I",
                              "Bella Vista",
                              "Asturias",
                              "Arenal Puerta Tepepan",
                              "Villa Centroamericana (U Hab)",
                              "Sta Isabel Industrial",
                              "Santo Tomas",
                              "Santa Maria Nativitas (Pblo)",
                              "San Pedro (Barr)",
                              "Ventura Perez De Alba",
                              "Peralvillo I",
                              "Paseos Del Sur",
                              "Narvarte I",
                              "Narciso Mendoza Villa Coapa Supermanzana 8 (U Hab)",
                              "Molino Del Rey",
                              "Tepepan (Ampl)",
                              "La Pera Xochinahuac (U Hab)",
                              "La Loma",
                              "Justo Sierra",
                              "Hipodromo I",
                              "Guadalupe Del Moral",
                              "San Alvaro",
                              "Residencial Zacatenco",
                              "Puente Colorado (Ampl)",
                              "Providencia (Ampl)",
                              "Lomas De La Era",
                              "Lomas De Las Aguilas",
                              "Lomas De Los Angeles Tetelpan",
                              "Anahuac Los Manzanos",
                              "Ampliacion Miguel Hidalgo 3a Secc",
                              "Ajusco Huayamilpas",
                              "Zentlapatl",
                              "Emilio Portes Gil Pemex Picacho (U Hab)",
                              "Solidaridad El Salado (U Hab)",
                              "Santa Cruz Aviacion",
                              "Los Morales (Polanco)",
                              "Avante",
                              "Copilco El Bajo",
                              "Villa Quietud (Fracc)",
                              "Unidades Habitacionales De Tenorios",
                              "Santa Cruz Meyehualco (U Hab) I",
                              "Santa Catarina Yecahuizotl (Pblo)",
                              "Santa Anita",
                              "Santa Maria La Ribera Ii",
                              "San Miguel  Xicalco (Pblo)",
                              "San Juan De Aragon 1a Seccion (U Hab) I",
                              "San Diego Churubusco",
                              "San Felipe De Jesus Iii",
                              "Popotla I",
                              "Pensil Norte",
                              "Penon Viejo (U Hab)",
                              "Pedregal De Sto Domingo Viii",
                              "Pedregal De Sto Domingo Iii",
                              "Paraje Zacatepec",
                              "Narciso Mendoza-Villa Coapa Super Manzana 7 (U Hab)",
                              "Nino Jesus (Barr)",
                              "Moctezuma 1a Seccion",
                              "Merced Gomez",
                              "Guadalupe",
                              "San Antonio Culhuacan (Barr)",
                              "Roma Norte Ii",
                              "Reforma Politica I",
                              "El Rosario",
                              "El Jaguey-Estacion Pantaco",
                              "Del Valle Vii",
                              "Los Olivos (U Hab)",
                              "Lomas De Becerra (U Hab)",
                              "Lindavista Vallejo (U Hab)",
                              "Lomas De Plateros (U Hab) Ii",
                              "Agricola Oriental Iv",
                              "La Malinche",
                              "Infonavit Iztacalco (U Hab) I",
                              "Ferreria",
                              "Juan Escutia Iii",
                              "Francisco Villa (U Hab)",
                              "Ex Hacienda Coapa",
                              "Venustiano Carranza",
                              "Albert",
                              "San Andres Totoltepec (Pblo)",
                              "Santa Maria Tepepan (Pblo)",
                              "Joyas Vallejo (U Hab)",
                              "El Tianguillo",
                              "Prados De Coyoacan",
                              "Viveros De Coactetlan",
                              "Vallejo I",
                              "Sevilla",
                              "San Simon Ticumac",
                              "Santa Cruz De Las Salinas",
                              "San  Miguel Amantla (Pblo)",
                              "San Juan De Aragon 3a Seccion (U Hab) Ii",
                              "San Jeronimo Aculco - Lidice (Pblo)",
                              "Popular Rastro",
                              "Penitenciaria (Ampl)",
                              "Parque San Andres",
                              "Obrera I",
                              "Torre Blanca (Ampl)",
                              "La Otra Banda",
                              "La Asuncion (Barr)",
                              "Jaime Torres Bodet",
                              "El Reloj",
                              "Coyuya (Fracc)",
                              "Constitucion De 1917 I",
                              "Coapa 2a Seccion-Ramos Millan",
                              "Lomas Estrella  Iii (U Hab)",
                              "Lomas Altas",
                              "Libertad",
                              "Alpes",
                              "La Joya",
                              "Ermita Zaragoza (U Hab) I",
                              "Nicolas Bravo",
                              "Atenor Salas",
                              "Villa Olimpica Liberador Miguel Hidalgo (U Hab)",
                              "Veronica Anzures",
                              "Unidades Habitacionales De Santa Ana Poniente I",
                              "San Miguel Ajusco (Pblo)",
                              "San Francisco Culhuacan (Pblo)",
                              "San Esteban (Barr)",
                              "San Jose De Los Cedros I",
                              "Petrolera (Ampl)",
                              "Nextengo (Barr)",
                              "Obrera Ii",
                              "La Pila",
                              "La Cebada",
                              "Joyas Del Pedregal (Fracc)",
                              "Jesus Del Monte",
                              "Jardines En La Montana",
                              "Isidro Fabela Ii (Oriente)",
                              "Independencia San Ramon (U Hab)",
                              "Ignacio Zaragoza I",
                              "San Antonio (Fracc)",
                              "Ramos Millan Bramadero I",
                              "Puebla",
                              "El Divisadero",
                              "Del Valle I",
                              "Del Gas",
                              "Ctm Viii Culhuacan (U Hab)",
                              "Colinas Del Sur",
                              "Ctm V Culhuacan (U Hab)",
                              "Cola De Pato",
                              "Ma Esther Zuno De Echeverria-Tlalpuente",
                              "Lomas De Memetla",
                              "Agricola Oriental V",
                              "5 De Mayo",
                              "Croc Culhuacan Secc 6 (U Hab)",
                              "Floresta-Prado-Vergel Coapa",
                              "Bondojito",
                              "Belisario Dominguez",
                              "Barranca Seca",
                              "Argentina Antigua",
                              "Torres San Antonio (U Hab)",
                              "Villa Hermosa",
                              "Tres Estrellas",
                              "Stunam Culhuacan (U Hab)",
                              "Buenos Aires",
                              "Valentin Gomez Farias",
                              "Santa Ursula Coyoacan",
                              "Santa Lucia (Barr)",
                              "San Pedro Martir (Pblo)",
                              "San Francisco (Barr)",
                              "Progreso Nacional (Ampl)",
                              "Pedregal De Las Aguilas",
                              "Pantitlan Iv",
                              "Narvarte V",
                              "Industrial I",
                              "Hogar Y Seguridad/Nueva Santa Maria",
                              "Roma Norte Iii",
                              "Presidentes Ejidales Segunda Seccion",
                              "Emiliano Zapata (U Hab)",
                              "Doctores Iv",
                              "Daniel Garza (Ampl)",
                              "Cuchilla De Padierna",
                              "Magdalena De Las Salinas",
                              "Lomas De San Lorenzo Ii",
                              "Lomas De Reforma (Lomas De Chapultepec)",
                              "Lomas De Puerta Grande",
                              "Anahuac Ii",
                              "8a De San Miguel (Ampl)",
                              "Memetla",
                              "El Molino_",
                              "Juarez",
                              "Buenavista I",
                              "Bosques De Las Lomas",
                              "Lomas De Vista Hermosa",
                              "Santiago Tepalcatlalpan (Pblo)",
                              "Santa Cruz Acalpixca (Pblo)",
                              "San Mateo Xalpa (Pblo)",
                              "San Mateo Tlaltenango (Pblo)",
                              "San Lucas (Barr)",
                              "San Lorenzo Xicotencatl (Pblo)",
                              "Portales Oriente",
                              "Popular Sta Teresa",
                              "Polanco Reforma (Polanco)",
                              "Plan De Ayala",
                              "Nueva Atzacoalco Ii",
                              "Tlalcoligia",
                              "Tlacamaca",
                              "La Noria",
                              "La Cruz",
                              "Jardines De San Lorenzo",
                              "Independencia Batan Norte (U Hab)",
                              "Iman",
                              "Guadalupe Insurgentes",
                              "Reforma Social",
                              "Real Del Moral (Fracc)",
                              "Granada",
                              "Estrella",
                              "Defensores De La Republica",
                              "Ctm Vi Culhuacan (U Hab)",
                              "Culhuacan (Pblo)",
                              "Los Sauces (Fracc)",
                              "Lindavista I",
                              "Chapultepec Morales (Polanco)",
                              "Centro Viii",
                              "Arboledas Del Sur",
                              "7 De Julio (Ampl)",
                              "Ejto Constitucionalista,Supermanzana Iii (U Hab)",
                              "Cantera Puente De Piedra",
                              "Anahuac Peralitos",
                              "Centro V",
                              "Abdias Garcia Soto",
                              "Vista Alegre",
                              "Unidades Habitacionales De Santa Ana Poniente Ii",
                              "Vistas Del Pedregal",
                              "Valle Escondido",
                              "Santa Cruz Xochitepec (Pblo)",
                              "Santa Lucia Reacomodo",
                              "San Marcos (Barr)",
                              "Pedregal De Sto Domingo Vii",
                              "Pedregal De Santa Ursula Ii",
                              "Palo Alto (Granjas)",
                              "Miravalle",
                              "Un Hogar Para Cada Trabajador",
                              "La Draga",
                              "Ignacio Zaragoza Ii",
                              "Guerrero Ii",
                              "Presidentes 1ra (Ampl)",
                              "Presidentes",
                              "Prado Coapa 2a Seccion",
                              "Gabriel Ramos Millan",
                              "Deportiva Pensil",
                              "Chapultepec Polanco (Polanco)",
                              "Centro Urbano Presidente Aleman (U Hab)",
                              "Centro Iv",
                              "10 De Mayo",
                              "La Conchita Ii",
                              "Rancho Los Colorines (Fracc)",
                              "Ex Ejido San Francisco Culhuacan Ii",
                              "Caltongo (Barr)",
                              "Boscoso (U Hab)",
                              "Torres Toreo",
                              "Tlatilco (U Hab)",
                              "Lomas De  Padierna I",
                              "Juan Gonzalez Romero",
                              "Progreso Nacional Ii",
                              "Granjas Coapa Oriente",
                              "El Rosedal Ii",
                              "Del Valle Ii",
                              "De La Candelaria (Pblo)",
                              "Lomas Del Chamizal",
                              "Ciudad Jardin",
                              "Arboledas",
                              "Aragon La Villa (Aragon)",
                              "Agricola Oriental Ii",
                              "7 De Noviembre",
                              "Centro Iii",
                              "Maria Del Carmen",
                              "Independencia Batan Sur (U Hab)",
                              "Lomas De San Bernabe",
                              "Tierra Unida",
                              "Ex Ejido San Francisco Culhuacan Iii",
                              "Capultitlan",
                              "Alvaro Obregon_ (Fracc)",
                              "Cuitlahuac 3 Y 4 (U Hab)",
                              "Villa Panamericana 1era. Seccion (U Hab)",
                              "Santa Maria Nonoalco",
                              "Santa Maria Aztahuacan (Ej) Ii",
                              "San Lucas Xochimanca (Pblo)",
                              "Portales Iv",
                              "Pedregal De Sto Domingo I",
                              "Pedregal De Sto Domingo Ii",
                              "Pedregal De La Zorra",
                              "Olivar Del Conde 1ra Seccion I",
                              "Olimpica",
                              "Santiago Zapotitlan (Pblo)",
                              "Santa Maria La Ribera Iv",
                              "San Pablo Tepetlapa (Pblo)",
                              "San Jose Insurgentes",
                              "Penon De Los Banos",
                              "Pedregal De Sn Nicolas 2a Secc",
                              "Pedregal De Santa Ursula I",
                              "Parque Residencial San Antonio (U Hab)",
                              "Paraje El Caballito",
                              "Navidad (Granjas De Navidad)",
                              "Napoles",
                              "Modelo (U)",
                              "Sindicato Mexicano De Electricistas",
                              "Jardines Del Llano-U.H. Villa Tlatempa",
                              "Tlalpan Centro",
                              "Tepeyac Insurgentes",
                              "Mesa Los Hornos,Texcaltenco",
                              "La Pradera",
                              "La Magdalena Atlitic (Pblo)",
                              "Jardines De La Palma (Huizachito)",
                              "Jardines Del Pedregal",
                              "Hogar Y Redencion",
                              "Hipodromo Ii",
                              "Granjas Mexico I",
                              "Residencial Insurgentes Sur (U Hab)",
                              "Rincon Del Bosque",
                              "Cuchilla Del Tesoro",
                              "Cuauhtemoc Pensil",
                              "Lomas De San Bernabe (Ampl)",
                              "Loma Del Padre",
                              "Loma De La Palma",
                              "Lindavista Ii",
                              "Leyes De Reforma 1a Seccion",
                              "Algarin",
                              "San Mateo (Barr)",
                              "2a Ampliacion Santiago Acahualtepec Ii",
                              "El Bosque Seccion Torres",
                              "Haciendas De Coyoacan (Fracc)",
                              "Estrella Del Sur",
                              "Los Cipreses",
                              "El Arbolillo 2 (U Hab)",
                              "Santa Fe",
                              "San Rafael",
                              "Verano",
                              "Pensador Mexicano Ii",
                              "Pedregal De Sn Nicolas 3a Secc",
                              "Pedregal De Santa Ursula Iii",
                              "Pantitlan I",
                              "Tacuba",
                              "Las Campanas",
                              "Janitzio",
                              "Jorge Negrete",
                              "Irrigacion",
                              "Industrial Vallejo",
                              "Reforma Pensil",
                              "Reforma Iztaccihuatl Sur",
                              "Puente Blanco",
                              "Presidentes Ejidales Primera Seccion",
                              "General Pedro Maria Anaya",
                              "El Yaqui",
                              "Cuauhtemoc",
                              "Cuadrante De San Francisco",
                              "Credito Constructor",
                              "Cove",
                              "Cultura Maya",
                              "Lomas Virreyes (Lomas De Chapultepec)",
                              "Llano Redondo",
                              "Anzures",
                              "Alfonso Xiii",
                              "Residencial Los Pinos (U Hab)",
                              "Felipe Pescador",
                              "Federal",
                              "Anahuac Dos Lagos",
                              "Viaducto  - Balbuena (Conj Hab)",
                              "Valle Del Sur",
                              "Barrio La  Lonja",
                              "Atlantida",
                              "Bellavista (U Hab)",
                              "Coltongo",
                              "Xotepingo",
                              "Viejo Ejido Santa Ursula Coapa",
                              "Selene 1a Secc",
                              "San Salvador Xochimanca",
                              "San Rafael Ticoman (Barr)",
                              "San Rafael I",
                              "San Nicolas Totolapan (Pblo)",
                              "Vicente Guerrero Super Manzana 2 (U Hab)",
                              "San Juan Xalpa Ii",
                              "Pedregal De Sn Nicolas 1a Secc",
                              "Pasteros",
                              "Nueva Oriental Coapa-Ex Hacienda Coapa",
                              "Narvarte Iii",
                              "La Patera-Condomodulos (U Hab)",
                              "Granjas Estrella I",
                              "Ejto De Ote Ii (U Hab)",
                              "Ctm Atzacoalco (U Hab)",
                              "Corpus Christy",
                              "Constitucion De 1917 Ii",
                              "Lomas De Chapultepec Ii",
                              "Aquiles Serdan",
                              "Angel Zimbron",
                              "Ampliacion Miguel Hidalgo 2a Secc",
                              "12 De Diciembre",
                              "Residencial Emperadores",
                              "Los Padres",
                              "Maza",
                              "Centro Urbano (U Hab)",
                              "Gertrudis Sanchez 3a Seccion",
                              "Villa Gustavo A Madero",
                              "San Nicolas Totolapan",
                              "San Francisco Tetecala (Pblo)",
                              "Portales I",
                              "Periodista",
                              "Paraiso",
                              "Obrera Iv",
                              "Tabacalera",
                              "La Purisima Ticoman (Barr)",
                              "La Preciosa",
                              "Jardin Balbuena I",
                              "Integracion Latinoamericana (U Hab)",
                              "Heroes De Padierna I",
                              "Romulo Sanchez-San Fernando (Barr)-Pena Pobre",
                              "Romero De Terreros",
                              "Residencial Maria Isabel",
                              "Presidentes 2da (Ampl)",
                              "Gertrudis Sanchez 1a Seccion",
                              "El Rosal",
                              "El Parque",
                              "Country Club",
                              "Issfam Las Armas (U Hab)",
                              "Los Reyes (Barr)",
                              "Lomas Estrella 2a Secc Ii",
                              "Chalma De Guadalupe Ii",
                              "Centro Vii",
                              "Ampliacion Miguel Hidalgo 4a Secc",
                              "Anahuac Mariano Escobedo",
                              "Alvaro Obregon",
                              "Centro Ii",
                              "Ex Hacienda San Juan De Dios",
                              "Pemex Lindavista (U Hab)",
                              "Aviacion Civil (Ampl)",
                              "Insurgentes Mixcoac",
                              "Arenal Guadalupe Tlalpan",
                              "Industrial Ii",
                              "Guadalupe Tepeyac",
                              "San Juan Ixtayopan (Pblo)",
                              "Villa Panamericana 4ta. Seccion (U Hab)",
                              "Valle Del Tepeyac",
                              "Santa Maria Tomatlan (Ampl)",
                              "San Pedro Iztacalco (Barr)",
                              "San Clemente",
                              "Piloto (Adolfo Lopez Mateos)",
                              "Petrolera",
                              "Paseos De Taxquena I",
                              "Olivar Del Conde 2da Seccion I",
                              "Nativitas",
                              "Narvarte Vi",
                              "Moderna",
                              "Modelo Pensil",
                              "La Nopalera",
                              "Ejto Constitucionalista",
                              "Del Valle Vi",
                              "Constitucion De La Republica",
                              "Los Volcanes",
                              "Merced Balbuena",
                              "Lomas De Chapultepec I",
                              "Lomas De Bezares",
                              "Adolfo Ruiz Cortines Ii",
                              "Francisco Villa",
                              "Extremadura Insurgentes",
                              "Esperanza",
                              "Escuadron 201",
                              "Torres San Pedro (U Hab)",
                              "San Pablo Oztotepec (Pblo)",
                              "Ajusco Ii",
                              "Santa Apolonia (Barr)",
                              "San Pedro De Los Pinos",
                              "San Pedro Cuajimalpa (Pblo)",
                              "San Lorenzo La Cebada I",
                              "San Juan De Aragon 4a  Y 5a Seccion (U Hab) Ii",
                              "San Juan De Aragon 4a  Y 5a Seccion (U Hab) I",
                              "San Francisco Tlaltenco (Pblo)",
                              "Pedregal De Sto Domingo Vi",
                              "Pedregal De Santa Ursula Iv",
                              "Tolteca",
                              "Tlatilco",
                              "Tlacuitlapa 2do Reacomodo (Ampl)",
                              "Las Aguilas (Ampl)",
                              "Jardines De Coyoacan (Fracc)",
                              "Isssfam No. 1 (U Hab)-Villa Tlalpan",
                              "San Bernabe (Barr)",
                              "Pro Hogar I",
                              "Granada (Ampl)",
                              "Garcimarrero",
                              "Doctores V",
                              "Del Valle Iii",
                              "C T M Aragon (U)",
                              "Copilco El Alto",
                              "Lomas De Tetelpan",
                              "Apatlaco",
                              "Media Luna",
                              "Centro De Azcapotzalco",
                              "Tres Fuentes (U Hab)",
                              "Ex-Hacienda El Rosario",
                              "Bahia (U Hab)",
                              "Cerro Prieto",
                              "Jardines Coapa-Belisario Dominguez",
                              "Los Reyes (Ampl)",
                              "Bosques De Chapultepec (Polanco)",
                              "Santa Lucia (Pblo)",
                              "Morelos Iii",
                              "Tetelpan",
                              "Manzanastitla",
                              "Pro Hogar Ii",
                              "Morales Seccion Alameda (Polanco)",
                              "Jardines De San Juan",
                              "Heroes De Churubusco",
                              "Heroe De Nacozari",
                              "Privada Centenario",
                              "Del Valle V",
                              "Copilco Universidad",
                              "Condesa",
                              "Club De Golf Mexico-San Buenaventura",
                              "Lomas De San Angel Inn",
                              "Alianza Popular Revolucionaria Poniente (U Hab)",
                              "Alianza Popular Revolucionaria Oriente (U Hab)",
                              "1ra Victoria Seccion Bosques",
                              "5to Tramo De 20 De Noviembre",
                              "24 De Abril",
                              "Ninos Heroes De Chapultepec",
                              "Barrio 18",
                              "Cacama",
                              "Atlampa",
                              "El Manto-Plan De Iguala",
                              "Agricola Metropolitana",
                              "Cuitlahuac 1 Y 2 (U Hab)",
                              "Chimalcoyoc",
                              "Xaltocan (Barr)",
                              "Villa De Aragon (Fracc)",
                              "San Mateo",
                              "San Bartolo Atepehuacan (Pblo)",
                              "Petrolera Taxquena",
                              "Pedregal De Sn Nicolas 4a Secc Ii",
                              "Narvarte Iv",
                              "Cuchilla Agricola Oriental",
                              "Consejo Agrarista Mexicano I",
                              "Loreto",
                              "Lorenzo Boturini",
                              "Los Girasoles Iii",
                              "Lomas De Sotelo",
                              "Lomas De Plateros (U Hab) I",
                              "Loma Hermosa (Conj Hab)",
                              "Ampliacion Ramos Millan",
                              "Aldana",
                              "Ajusco Iii",
                              "Villa Del Puente Fovissste  (U Hab)",
                              "Actipan",
                              "San Juan",
                              "El Molino",
                              "Fiviport (U Hab)",
                              "Felipe Angeles",
                              "Del Bosque (Polanco)",
                              "Villa De Aragon",
                              "La Virgen 1170 (U Hab)",
                              "Bosques De Tarango",
                              "Carola (U Hab)",
                              "Belen De Las Flores (U Hab)",
                              "Bejero",
                              "Tlacoquemecatl Del Valle",
                              "Tepalcates Ii",
                              "Miguel Hidalgo",
                              "Mexico Nuevo",
                              "La Habana",
                              "La Fama",
                              "La Concepcion (Barr)",
                              "Jardines Del Ajusco",
                              "Isidro Fabela I (Poniente)",
                              "Jardines Del Sur",
                              "Real Del Sur-Villas Del Sur-Residencial Acoxpa",
                              "El Rosedal I",
                              "Torres De Mixcoac (U Hab)",
                              "Texcalco",
                              "Minas De Cristo",
                              "Jardin Balbuena Iii",
                              "Jamaica",
                              "Guerrero I",
                              "San Angel",
                              "Romero De Terreros (Fracc)",
                              "Prado Coapa 3a Seccion-Potrero Acoxpa",
                              "El Rosario C (U Hab)",
                              "Del Recreo",
                              "Legaria",
                              "Centro Vi",
                              "Aragon Inguaran",
                              "2a Ampliacion Santiago Acahualtepec I",
                              "Acueducto",
                              "Insurgentes",
                              "Periodista Francisco Zarco",
                              "Venustiano Carranza (Ampl)",
                              "Miguel Aleman",
                              "Bosque Residencial Del Sur (Fracc)",
                              "Asturias (Ampl)",
                              "San Andres Mixquic (Pblo)",
                              "Xalpa",
                              "Victoria De Las Democracias",
                              "Santiago Ahuizotla (Pblo)",
                              "Santa Isabel Tola (Pblo)",
                              "San Juan Tepenahuac (Pblo)",
                              "San Juan De Aragon 2a Seccion (U Hab) I",
                              "San Bartolo Ameyalco",
                              "Portales Ii",
                              "Postal",
                              "Nueva Vallejo",
                              "Narciso Bassols (U Hab)",
                              "San Andres (Pblo)",
                              "Quetzalcoatl 3",
                              "Fuentes Y Pedregal De Tepepan",
                              "Doctores I",
                              "Dm Nacional",
                              "Corredor Santa Fe",
                              "Coapa-Villa Cuemanco",
                              "Los Girasoles Ii",
                              "Lomas De Barrilaco (Lomas De Chapultepec)",
                              "Anahuac I",
                              "Ampliacion Candelaria",
                              "Amado Nervo",
                              "Ahuatenco",
                              "Cantil Del Pedregal",
                              "Ano De Juarez",
                              "Romero De Terreros (Cond)",
                              "San Miguel Topilejo (Pblo)",
                              "Abraham Gonzalez",
                              "Iztaccihuatl",
                              "La Cantera (U Hab)",
                              "Campamento 2 De Octubre Ii",
                              "Torre Blanca",
                              "Tlacotal Ramos Millan",
                              "Tacubaya",
                              "Simon  Bolivar",
                              "Juristas",
                              "Roma Sur Ii",
                              "Villas Del Pedregal (U Hab)",
                              "Villa Coyoacan",
                              "Un Hogar Para Nosotros",
                              "Santo Domingo (Pblo)",
                              "Santiago Sur (Barr)",
                              "Santa Maria Insurgentes",
                              "Popotla Ii",
                              "Piloto (Adolfo Lopez Mateos) (Ampl)",
                              "Pedregal De San Angel (Ampl)",
                              "Nueva Tenochtitlan",
                              "Moctezuma 2a Seccion I",
                              "La Magdalena Petlacalco (Pblo)",
                              "Santa Teresa",
                              "San Rafael Ii",
                              "San Miguel Chapultepec Ii",
                              "San Miguel Chapultepec I",
                              "San Lorenzo Tezonco (Pblo)",
                              "San Jose Aculco",
                              "San Jose De La Escalera",
                              "Pensil San Juanico",
                              "Pedregal De San Francisco (Fracc)",
                              "Paseos De Churubusco",
                              "Nueva Sta Anita",
                              "Narciso Mendoza-Villa Coapa Super Manzana 2 (U Hab)",
                              "Moctezuma 2a Seccion Ii",
                              "Tlaxpana",
                              "Tezozomoc",
                              "Las Arboledas",
                              "Monte De Piedad",
                              "Jalalpa El Grande",
                              "Oxtopulco Universidad",
                              "Heroes De Padierna",
                              "San Angel Inn",
                              "Rincon De La Bolsa",
                              "Residencial La Escalera (Fracc)",
                              "El Retono",
                              "Ejidos San Juan De Aragon 1a Seccion (U Hab)",
                              "Ejidos De San Pedro Martir I (Norte)",
                              "Del Valle Iv",
                              "Cuitlahuac (U Hab)",
                              "Cuchilla Pantitlan",
                              "Conjunto Habitacional Pedregal Del Lago",
                              "Magdalena  Mixhuca (Pblo)",
                              "Lomas De San Lorenzo I",
                              "Lomas Estrella 1a Secc (Fracc)",
                              "Alianza Popular Revolucionaria Norte (U Hab)",
                              "Alcantarilla",
                              "Aeronautica Militar",
                              "Acueducto De Guadalupe (U Hab)",
                              "Juan Escutia I",
                              "Escandon Ii",
                              "Ex Ejido San Francisco Culhuacan I",
                              "Atlamaya",
                              "La Pradera I (U Hab)",
                              "La Conchita I",
                              "Juventino Rosas Ii",
                              "Insurgentes Cuicuilco",
                              "Ricardo Flores Magon (Ampl)",
                              "Rancho El Rosario",
                              "Predio La Angostura",
                              "Prados Del Rosario",
                              "Del Nino Jesus (Barr)",
                              "El Arenal 4a Seccion",
                              "Ctm Vii Culhuacan (U Hab)",
                              "Lomas De Guadalupe",
                              "Cerro De La Estrella I",
                              "Infonavit Iztacalco (U Hab) Ii",
                              "Ermita",
                              "Cerro De La Estrella Ii",
                              "Fuentes Brotantes Miguel Hidalgo (U Hab)",
                              "Fuego Nuevo",
                              "Flor De Maria",
                              "Artes Graficas",
                              "Viaducto Piedad",
                              "Xoco",
                              "Santa Maria (U Hab)",
                              "Bosques De Tetlameya",
                              "Belvedere",
                              "Arenal",
                              "Hermosillo",
                              "Sinatel",
                              "Santa Fe (U Hab)",
                              "San Juan De Aragon 7 Secc (U Hab) I",
                              "Pantitlan Ii",
                              "Nonoalco-Tlatelolco (U Hab) Ii",
                              "Nonoalco",
                              "Narciso Mendoza-Villa Coapa Super Manzana 3 (U Hab)",
                              "Cruz Blanca",
                              "Villa Lazaro Cardenas",
                              "Santo Tomas Ajusco (Pblo)",
                              "Santa Rosa Xochiac (Pblo)",
                              "Santa Ines",
                              "San Pedro De Los  Pinos",
                              "San Lorenzo Acopilco (Pblo)",
                              "San Lorenzo La Cebada Ii",
                              "Plazuela Del Pedregal",
                              "Obrero Popular",
                              "Nueva Santa Maria",
                              "Nueva Espana",
                              "Mixcoac",
                              "Torres Lindavista (Fracc)",
                              "Mirador 1a Secc",
                              "La Mexicana",
                              "La Concepcion",
                              "Jardin Azpeitia",
                              "Jacarandas",
                              "Granjas Mexico Ii",
                              "Romero Rubio",
                              "Prado Churubusco",
                              "El Eden",
                              "El Caracol",
                              "Ctm X Culhuacan (U Hab)",
                              "Ciudad De Los Deportes",
                              "Lomas De Tarango",
                              "Lomas De Axomiatla",
                              "Leyes De Reforma 3a Seccion I",
                              "Alamos I",
                              "Agricola Oriental I",
                              "Rincon Las Hadas-Villa Royale-Fuentes Y Arconada Coapa",
                              "Florida",
                              "Espartaco",
                              "Emiliano Zapata (Ampl)",
                              "Fovissste San Pedro Martir ( U Hab)",
                              "10 De Abril",
                              "Ex-Escuela De Tiro",
                              "Villa Panamericana 2da. Seccion (U Hab)",
                              "Pensil Sur",
                              "Insurgentes San Borja",
                              "Banjidal",
                              "San Martin Xochinahuac (Pblo)",
                              "Pensador Mexicano I",
                              "Paseos De Taxquena Ii",
                              "Pedregal Del Maurel",
                              "Palmitas (Polanco)",
                              "Pantitlan V",
                              "Nueva Atzacoalco I",
                              "Nueva Industrial Vallejo (Fracc)",
                              "Tlacopac",
                              "Letran Valle",
                              "Las Aguilas",
                              "Jose Maria Pino Suarez",
                              "Jardin Balbuena Ii",
                              "Hacienda De Guadalupe Chimalistac",
                              "Roma Norte I",
                              "San Juan De Aragon 6a Seccion (U Hab) I",
                              "Granjas Coapa",
                              "Garcimarrero Norte",
                              "Magdalena Atlazolpa (Pblo)",
                              "Lomas Quebradas",
                              "Lomas De  Padierna Ii",
                              "Lomas Estrella 2a Secc I",
                              "Ampliacion San Francisco Culhuacan (Ej)",
                              "Altillo (Cond Altillo Universidad)",
                              "Albarradas (U Hab)",
                              "Alamos Ii",
                              "Ajusco I",
                              "Santa Cruz (Barr)",
                              "La Mexicana (Ampl)",
                              "Villa Progresista",
                              "Tizampampano",
                              "La Angostura",
                              "Pedregal 2 (Conj Hab)",
                              "Transito",
                              "Cafetales I (Rdcial)",
                              "Buenavista Ii",
                              "Cosmopolita (Ampl)",
                              "San Simon Tolnahuac",
                              "San Pedro Xalpa (Ampl) Ii"), #Lista de Colonias
                  width = "220px"),
      
      radioButtons("radio", label = h5("Tipo de propiedad"), 
                   choices = list("Cuarto Privado" = "Private room", 
                                  "Departament o Casa completa" = "Entire home/apt",
                                  "Cuarto compartido" = "Shared room"), # El valor 0 , 1 será diferente para la base que se esta montando.
                   selected = 16),
      numericInput("titlesize", "No de Cuartos:", value = 1, min = 1, max = 50),
      numericInput("titlesize", "No de Baños:", value = 1, min = 1, max = 50),
      
      #Botones para calculo, actualización y eliminación
      actionButton("bus_refresh", "Calcular Tarifa"), # "bus_refresh" argumento para acción del boton.
      actionButton("bus_refresh", "Actualizar Tarifa "),
      actionButton("bus_refresh", "Eliminar Tarifa"),
      
      hr(),
      tags$div(class="header", checked=NA,
               tags$p("Esta analisis te da una estimación del precio al que podrìas rentar tu propiedad basado en la datos provistos por la aplicación AirBnb"))),
    
    
    #Panel derecha 
    # Panel central para mostrar todos los resultados
    mainPanel(
      plotOutput("stateMap"),
      h4("Gráfica de delitos a casa habitacion en los ultimos años para esa alcaldia seleccionada", align = "left"),
      plotOutput("phonePlot"),
      tableOutput("contents"),
      h4("Observations"),
      tableOutput("view"),
      renderPlot({
        plot(x = selected_trends()$date, y = selected_trends()$close, type = "l",
             xlab = "Date", ylab = "Trend index")
      })
    )
    
    
  )
)


server <- function(input, output, session) {
  filedata <- reactive({
    infile <- input$file1
    if (is.null(infile)){
      return(NULL)      
    }
    read.csv(infile$datapath)
  })
  
  
  library(dplyr)
  library(tidyverse)
  library(ggplot2)
  library(fiftystater)
  
  
  output$column <- renderUI({
    df <- filedata()
    if (is.null(df)) return(NULL)
    #  items=names(df) # add back in if you want all columns
    nums <- sapply(df, is.numeric) # keep only number columns
    items=names(nums[nums]) # keep only number columns
    names(items)=items
    selectInput("bubble", "Choose column to map to dot size", items)
  })
  
  output$color <- renderUI({
    df <- filedata()
    if (is.null(df)) return(NULL)
    #  items=names(df) # add back in if you want all columns
    nums <- sapply(df, is.numeric) # keep only number columns
    items=names(nums[nums]) # keep only number columns
    names(items)=items
    selectInput("color", "Choose column for color",items)
  })
  
   output$contents = renderTable({
    df <- filedata()
    return(df)
  })
  
  
  output$stateMap <- renderPlot({
    
    df <- filedata()
    #df_subset <- subset(df, input$bubble > 0) # subsetting not working
    
    p3 <- ggplot() + geom_polygon(data=fifty_states, aes(x=long, y=lat, group = group),color="white", fill= "grey92") +
      geom_point(data = df, aes_string(x=df$lon, y=df$lat, size=input$bubble), color = input$color, shape = as.numeric(input$radio)) +
      scale_size(name="", range = c(input$low, input$high)) +
      ggtitle(input$title) + 
      guides(size=guide_legend(input$legend)) +
      theme_void() +
      theme(aspect.ratio=1.62/3, 
            plot.title = element_text(size = input$titlesize),
            legend.title=element_text(size= input$legendsize),
            text=element_text(family=input$family))
    p3
    
  })
  
  output$downloadPlot <- downloadHandler(
    filename = function() {paste('map-', Sys.Date(), '.png', sep='')},
    content = function(file) { 
      png(file, type='cairo')
      ggsave("storybench-mapmaker.png", width=14.4,height=7.43,units="in")
    },
    contentType = 'image/png'
  )
  
}


# Run the application 
shinyApp(ui = ui, server = server)
